### ISSUE TITLE
changing the board size before starting a game breaks the grid

### ISSUE THREAD

**Issue by roselino-quatro** [courselab/coral#104]
changing the game size to small or large on the settings menu before playing will make the grid size, snake size and fruit size to be inconsistent, diying will fix the bug

**Comment by TheoRiffel** [comment]
I identified where the bug ocurred. As soon as the game is launched the random position of the snake and apple were set to be in the grid "medio", but as soon as the game started in the other grids the random position according to the new grid were not updated. I will do a PR so solve this issue.
