### ISSUE TITLE
Delete merged branches.

### ISSUE THREAD

**Issue by monacofj** [courselab/coral#125]
There may be branches in the repo that have already been merged.
Please, revise closed PRs and delete all merged branches.

**Comment by gabrielarodriguesp** [comment]
On it.

**Comment by rodrigo-lex** [comment]
from `git branch -r --merged`, I get:
` origin/120-bug-speed-doesnt-reset-after-dying
  origin/21-enhancement-hard-mode
  origin/35-press-m-to-muteunmute-soundtrack
  origin/bug/10/fit-window-size
  origin/bug/3/update-movement
  origin/bug/31/energy-bar
  origin/bug/33/stuck-in-hard-mode
  origin/bug/39/draw-order-fix
  origin/bug/4/fruit-spawn-bug
  origin/bug/95/music-not-looping
  origin/bug/99/crash-on-highscore
  origin/code/cleanup
  origin/doc/113/changing-name-to-coral
  origin/doc/133/add-a-changelog
  origin/doc/146/reuse-compliance
  origin/documentation/77/instructions-on-readme
  origin/feat/1/update-contrib
  origin/feat/101/fruit-energy
  origin/feat/110/color-body-on-death
  origin/feat/13/display-paused-message
  origin/feat/18/dynamic-energy-bar
  origin/feat/24/add-music-and-sound-effetcs
  origin/feat/25/game-parameters
  origin/feat/35/mute_key
  origin/feat/44/stylized-head
  origin/feat/59/change-themes
  origin/feat/73/circular-apple
  origin/feat/78/stem-apple
  origin/feat/97/preference-indicator
  origin/fix-38-movementqueue
  origin/fix-39-pausemenu
  origin/fix/15/moving-while-paused
  origin/hot/41/stop-game-over-music
  origin/refactoring/116/create-fruits-base-class
  origin/v1.0.0
`
If there is no objection, I believe these branches should be removed and I intend to do so at the end of the day.

**Comment by de-abreu** [comment]
Removed all branches that aren't currently associated with an open Issue or Pull Request.
