### ISSUE TITLE
feat: Make movement wrap around the screen, as seen in Snake II

### ISSUE THREAD

**Issue by de-abreu** [courselab/coral#140]
As seen in the video: [Snake II](https://youtu.be/KcpRyIFU7Eg)

**Comment by monacofj** [comment]
Hm... I can only agree if that were an on/off option.
Perhaps that Nokia's modification of the original Snake was to make the game playable under the usability constraints of the device, as it makes the challenge considerably easier.

**Comment by de-abreu** [comment]
I see, then I propose changing it so that it is a property of playing the game at the easy mode. I'll modify it and send it towards the dev branch.
