### ISSUE TITLE
Non free font (CRITICAL)

### ISSUE THREAD

**Issue by monacofj** [courselab/coral#148]
According to some font distribution sites, the "GetVoid Grotesque" font used by the game is licensed under CC0.
Thought a more extensive search, however, some references lists it as free for non-comercial only, what makes it not open source.

To be safe, please, replace the font with another one that is guaranteed to be open source.

Then, add its license using  `REUSE.

**Comment by de-abreu** [comment]
After the game font was changed, there are instances of it clipping over the edges of the screen and over other text paragraphs.
![Screenshot From 2024-12-09 21-37-52](https://github.com/user-attachments/assets/be8e427e-6fdb-45f7-8129-1e45fdcd84ca)
![Screenshot From 2024-12-09 21-37-31](https://github.com/user-attachments/assets/157af86b-0c64-43d1-8436-82d895d869b2)
I'll tend to that.

**Comment by de-abreu** [comment]
The updated screens:
![Screenshot From 2024-12-10 19-32-20](https://github.com/user-attachments/assets/30aecb4f-3adf-4c90-aa1f-14928598452e)
![Screenshot From 2024-12-10 19-32-48](https://github.com/user-attachments/assets/40690878-8aa9-4a46-af2a-1ecf141b0379)
