### ISSUE TITLE
Bug: resizing more than once a game causes fruits and obstacle to stay outside of grid boarders.

### ISSUE THREAD

**Issue by TheoRiffel** [courselab/coral#189]
In version v1.0.0 there is a bug when changing sizes of grid more than once a game. Causes obstacles and fruits to stay outside of grid boarders.

**Comment by TheoRiffel** [comment]
![image](https://github.com/user-attachments/assets/770a1c78-a63e-4a78-848a-71de23d04255)

this bug occurs because the objects of apple, orange and the array of obstacles are not updated after the grid size is changed in this method center_prompt(). 

I analysed a bit and I expect this bug to be a little tricky to solve. Help is appreciated. Creating a branch to solve this bug

**Comment by rodrigo-lex** [comment]
fixed by #205!
