### ISSUE TITLE
Package binaries to be added to the v1.0.0 release.

### ISSUE THREAD

**Issue by de-abreu** [courselab/coral#220]
At the very least package for Linux, MacOS, and Windows in the x86_64. We recommend using [pyinstaller](https://pypi.org/project/pyinstaller/) for that. Update README with instructions for developing and for simply playing the effing game.

**Comment by de-abreu** [comment]
I'll handle the Linux side.

**Comment by monacofj** [comment]
We can release the source code now, and add distribution binaries later.
