### ISSUE TITLE
Snake covers energy bar

### ISSUE THREAD

**Issue by samuelsbonachela** [courselab/coral#39]
The energy bar is on top of some playable tiles but appears under the snake, so when the snake goes in the top left corner of the grid it's impossible to see the ernegy bar.

**Comment by raultel** [comment]
Hi!
Do you plan on tackling this issue yourself?

**Comment by lucasclaros** [comment]
I can work on it!

**Comment by samuelsbonachela** [comment]
I just fixed it, I'm going to send a PR now
