### ISSUE TITLE
Pause menu doesn't appear after pausing

### ISSUE THREAD

**Issue by Ensuo** [courselab/coral#46]
The menu with the "Paused" and "Press P to continue" do not appear after the game is paused.

**Comment by lucasclaros** [comment]
Could you explain this bug in more detail, @Ensuo ?

**Comment by Ensuo** [comment]
The problem that was happening was that, when the game was paused, the pause menu didn't appear. But this issue has already been finished, I forgot to link it to the pull request I've done. I'm sorry for the confusion
