### ISSUE TITLE
Enhancement: add option to change game volume 

### ISSUE THREAD

**Issue by vrveiga** [courselab/coral#56]
Add buttons/options to change game volume.

Would it be better to add the option in the configuration menu or use the '-' and '+' keys to decrease and increase sound?

**Comment by Petroncini** [comment]
I think it would be better for it to be an option on the menu as its more intuitive for the user. We would have to tell the player about the volume keys otherwise.

**Comment by vrveiga** [comment]
Makes sense, I'll start working on it.
