### ISSUE TITLE
Bug: unordered input processing

### ISSUE THREAD

**Issue by raultel** [courselab/coral#62]
The user input is not put in a queue, which leads to strange behaviors such as the snake killing itself when both left and right keys are pressed really quickly

**Comment by roselino-quatro** [comment]
is it related to #38 ? I am not sure if I understood what you meant, going left and then right should always kill you anyway because you're going to walk over yourself. Sorry if I am just misunderstanding

**Comment by Petroncini** [comment]
I added a queue to the movement system on PR #40. Is the previous bug from issue #38 persisting?

**Comment by raultel** [comment]
> I added a queue to the movement system on PR #40. Is the previous bug from issue #38 persisting?

my bad, I probably wasn't on the last version when I noticed that
snake movement is feeling great now!
